// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Manages Cloud Monitoring Metrics Scopes, and the monitoring of Google Cloud
/// projects and AWS accounts.
///
/// @Snippet(path: "MetricsScopesQuickstart")
public class MetricsScopesClient: Clients.MetricsScopesProtocol {
  let inner: any Clients.MetricsScopesStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `MetricsScopesClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.MetricsScopesStub = try Clients.MetricsScopesTransport(options)
    inner = Clients.MetricsScopesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.MetricsScopesLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Returns a specific `Metrics Scope`.
  ///
  /// @Snippet(path: "MetricsScopes_GetMetricsScope")
  public func getMetricsScope(
    request: GetMetricsScopeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope {
    try await self.inner.getMetricsScope(request: request, options: options)
  }

  /// Returns a list of every `Metrics Scope` that a specific `MonitoredProject`
  /// has been added to. The metrics scope representing the specified monitored
  /// project will always be the first entry in the response.
  ///
  /// @Snippet(path: "MetricsScopes_ListMetricsScopesByMonitoredProject")
  public func listMetricsScopesByMonitoredProject(
    request: ListMetricsScopesByMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse
  {
    try await self.inner.listMetricsScopesByMonitoredProject(request: request, options: options)
  }

  /// Adds a `MonitoredProject` with the given project ID
  /// to the specified `Metrics Scope`.
  ///
  /// @Snippet(path: "MetricsScopes_CreateMonitoredProject")
  public func createMonitoredProject(
    request: CreateMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createMonitoredProject(request: request, options: options)
  }

  /// Adds a `MonitoredProject` with the given project ID
  /// to the specified `Metrics Scope`.
  ///
  /// @Snippet(path: "MetricsScopes_CreateMonitoredProject")
  public func createMonitoredProject(
    withPolling: CreateMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<MonitoredProject> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<MonitoredProject>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try MonitoredProject(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createMonitoredProject(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<MonitoredProject>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a `MonitoredProject` from the specified `Metrics Scope`.
  ///
  /// @Snippet(path: "MetricsScopes_DeleteMonitoredProject")
  public func deleteMonitoredProject(
    request: DeleteMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteMonitoredProject(request: request, options: options)
  }

  /// Deletes a `MonitoredProject` from the specified `Metrics Scope`.
  ///
  /// @Snippet(path: "MetricsScopes_DeleteMonitoredProject")
  public func deleteMonitoredProject(
    withPolling: DeleteMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteMonitoredProject(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "MetricsScopes_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `MetricsScopesClient`.
  ///
  /// To mock `MetricsScopesClient` change your functions to receive
  /// `some MetricsScopesProtocol` or `any MetricsScopesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol MetricsScopesProtocol {
    /// See `MetricsScopesClient.getMetricsScope`.
    func getMetricsScope(request: GetMetricsScopeRequest) async throws
      -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope

    /// See `MetricsScopesClient.getMetricsScope`.
    func getMetricsScope(
      name: Swift.String,
    ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope

    /// See `MetricsScopesClient.listMetricsScopesByMonitoredProject`.
    func listMetricsScopesByMonitoredProject(request: ListMetricsScopesByMonitoredProjectRequest)
      async throws
      -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse

    /// See `MetricsScopesClient.createMonitoredProject`.
    func createMonitoredProject(request: CreateMonitoredProjectRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `MetricsScopesClient.createMonitoredProject`.
    func createMonitoredProject(withPolling: CreateMonitoredProjectRequest) async throws
      -> any GoogleCloudGax.PollableOperation<MonitoredProject>

    /// See `MetricsScopesClient.createMonitoredProject`.
    func createMonitoredProject(
      parent: Swift.String,
      monitoredProject: MonitoredProject?,
    ) async throws -> any GoogleCloudGax.PollableOperation<MonitoredProject>

    /// See `MetricsScopesClient.deleteMonitoredProject`.
    func deleteMonitoredProject(request: DeleteMonitoredProjectRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `MetricsScopesClient.deleteMonitoredProject`.
    func deleteMonitoredProject(withPolling: DeleteMonitoredProjectRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Void>

    /// See `MetricsScopesClient.deleteMonitoredProject`.
    func deleteMonitoredProject(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `MetricsScopesClient.getMetricsScope`.
    func getMetricsScope(
      request: GetMetricsScopeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope

    /// See `MetricsScopesClient.listMetricsScopesByMonitoredProject`.
    func listMetricsScopesByMonitoredProject(
      request: ListMetricsScopesByMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse

    /// See `MetricsScopesClient.createMonitoredProject`.
    func createMonitoredProject(
      request: CreateMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MetricsScopesClient.createMonitoredProject`.
    func createMonitoredProject(
      withPolling: CreateMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<MonitoredProject>

    /// See `MetricsScopesClient.deleteMonitoredProject`.
    func deleteMonitoredProject(
      request: DeleteMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MetricsScopesClient.deleteMonitoredProject`.
    func deleteMonitoredProject(
      withPolling: DeleteMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>
  }
}

// Default implementations
extension Clients.MetricsScopesProtocol {
  public func getMetricsScope(request: GetMetricsScopeRequest) async throws
    -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope
  {
    try await self.getMetricsScope(request: request, options: .init())
  }

  public func getMetricsScope(
    request: GetMetricsScopeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getMetricsScope(
    name: Swift.String,
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope {
    let request = GetMetricsScopeRequest().with {
      $0.name = name
    }
    return try await self.getMetricsScope(request: request)
  }

  public func listMetricsScopesByMonitoredProject(
    request: ListMetricsScopesByMonitoredProjectRequest
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse
  {
    try await self.listMetricsScopesByMonitoredProject(request: request, options: .init())
  }

  public func listMetricsScopesByMonitoredProject(
    request: ListMetricsScopesByMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createMonitoredProject(request: CreateMonitoredProjectRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createMonitoredProject(request: request, options: .init())
  }

  public func createMonitoredProject(
    request: CreateMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createMonitoredProject(withPolling: CreateMonitoredProjectRequest) async throws
    -> any GoogleCloudGax.PollableOperation<MonitoredProject>
  {
    try await self.createMonitoredProject(withPolling: withPolling, options: .init())
  }

  public func createMonitoredProject(
    withPolling: CreateMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<MonitoredProject> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<MonitoredProject>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createMonitoredProject(
    parent: Swift.String,
    monitoredProject: MonitoredProject?,
  ) async throws -> any GoogleCloudGax.PollableOperation<MonitoredProject> {
    let request = CreateMonitoredProjectRequest().with {
      $0.parent = parent
      $0.monitoredProject = monitoredProject
    }
    return try await self.createMonitoredProject(withPolling: request)
  }

  public func deleteMonitoredProject(request: DeleteMonitoredProjectRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteMonitoredProject(request: request, options: .init())
  }

  public func deleteMonitoredProject(
    request: DeleteMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteMonitoredProject(withPolling: DeleteMonitoredProjectRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Void>
  {
    try await self.deleteMonitoredProject(withPolling: withPolling, options: .init())
  }

  public func deleteMonitoredProject(
    withPolling: DeleteMonitoredProjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteMonitoredProject(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteMonitoredProjectRequest().with {
      $0.name = name
    }
    return try await self.deleteMonitoredProject(withPolling: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
