// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Represents a [Metrics
/// Scope](https://cloud.google.com/monitoring/settings#concept-scope) in Cloud
/// Monitoring, which specifies one or more Google projects and zero or more AWS
/// accounts to monitor together.
public struct MetricsScope: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of the Monitoring Metrics Scope.
  /// On input, the resource name can be specified with the
  /// scoping project ID or number. On output, the resource name is
  /// specified with the scoping project number.
  /// Example:
  /// `locations/global/metricsScopes/{SCOPING_PROJECT_ID_OR_NUMBER}`
  public var name: Swift.String = Swift.String()

  /// Output only. The time when this `Metrics Scope` was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when this `Metrics Scope` record was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The list of projects monitored by this `Metrics Scope`.
  public var monitoredProjects: [MonitoredProject] = []

  /// Initialize a new instance of `MetricsScope`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MetricsScope().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.metricsscope.v1.MetricsScope"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
