// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class MetricsScopesLogging: MetricsScopesStub {
    let inner: any MetricsScopesStub
    let logger: Logger

    public init(_ inner: any MetricsScopesStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-monitoring-metricsscope-v1"
      logger[metadataKey: "gcp.client.service"] = "monitoring"
      logger[metadataKey: "gcp.experimental.swift.client"] = "MetricsScopes"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getMetricsScope(
      request: GetMetricsScopeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMetricsScope",
        action: {
          (r: GetMetricsScopeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope
          in
          return try await self.inner.getMetricsScope(request: r, options: o)
        })
    }

    public func listMetricsScopesByMonitoredProject(
      request: ListMetricsScopesByMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMetricsScopesByMonitoredProject",
        action: {
          (r: ListMetricsScopesByMonitoredProjectRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse
          in
          return try await self.inner.listMetricsScopesByMonitoredProject(request: r, options: o)
        })
    }

    public func createMonitoredProject(
      request: CreateMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createMonitoredProject",
        action: {
          (r: CreateMonitoredProjectRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMonitoredProject(request: r, options: o)
        })
    }

    public func deleteMonitoredProject(
      request: DeleteMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteMonitoredProject",
        action: {
          (r: DeleteMonitoredProjectRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMonitoredProject(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
