// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class MetricsScopesRetry: MetricsScopesStub {
    let inner: any MetricsScopesStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any MetricsScopesStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getMetricsScope(
      request: GetMetricsScopeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMetricsScopeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope
          in
          return try await self.inner.getMetricsScope(request: r, options: o)
        })
    }

    public func listMetricsScopesByMonitoredProject(
      request: ListMetricsScopesByMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMetricsScopesByMonitoredProjectRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse
          in
          return try await self.inner.listMetricsScopesByMonitoredProject(request: r, options: o)
        })
    }

    public func createMonitoredProject(
      request: CreateMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMonitoredProjectRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMonitoredProject(request: r, options: o)
        })
    }

    public func deleteMonitoredProject(
      request: DeleteMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMonitoredProjectRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMonitoredProject(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
