// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Manages Cloud Monitoring Metrics Scopes, and the monitoring of Google Cloud
/// projects and AWS accounts.
///
/// @Snippet(path: "MetricsScopesQuickstart")
public final class MetricsScopesClient: Clients.MetricsScopesProtocol, Sendable {
  let inner: any Clients.MetricsScopesStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `MetricsScopesClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.MetricsScopesStub = try Clients.MetricsScopesTransport(options)
    inner = Clients.MetricsScopesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.MetricsScopesLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Returns a specific `Metrics Scope`.
  ///
  /// @Snippet(path: "MetricsScopes_GetMetricsScope")
  public func getMetricsScope(
    request: GetMetricsScopeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope {
    try await self.inner.getMetricsScope(request: request, options: options)
  }

  /// Returns a list of every `Metrics Scope` that a specific `MonitoredProject`
  /// has been added to. The metrics scope representing the specified monitored
  /// project will always be the first entry in the response.
  ///
  /// @Snippet(path: "MetricsScopes_ListMetricsScopesByMonitoredProject")
  public func listMetricsScopesByMonitoredProject(
    request: ListMetricsScopesByMonitoredProjectRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse
  {
    try await self.inner.listMetricsScopesByMonitoredProject(request: request, options: options)
  }

  /// Adds a `MonitoredProject` with the given project ID
  /// to the specified `Metrics Scope`.
  ///
  /// @Snippet(path: "MetricsScopes_CreateMonitoredProject")
  public func createMonitoredProject(
    request: CreateMonitoredProjectRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createMonitoredProject(request: request, options: options)
  }

  /// Adds a `MonitoredProject` with the given project ID
  /// to the specified `Metrics Scope`.
  ///
  /// @Snippet(path: "MetricsScopes_CreateMonitoredProject")
  public func createMonitoredProjectPollingUntilDone(
    request: CreateMonitoredProjectRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<MonitoredProject> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<MonitoredProject>.State in
      return try op._extractStatus(MonitoredProject.self)
    }
    let rawOp = try await self.createMonitoredProject(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<MonitoredProject>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a `MonitoredProject` from the specified `Metrics Scope`.
  ///
  /// @Snippet(path: "MetricsScopes_DeleteMonitoredProject")
  public func deleteMonitoredProject(
    request: DeleteMonitoredProjectRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteMonitoredProject(request: request, options: options)
  }

  /// Deletes a `MonitoredProject` from the specified `Metrics Scope`.
  ///
  /// @Snippet(path: "MetricsScopes_DeleteMonitoredProject")
  public func deleteMonitoredProjectPollingUntilDone(
    request: DeleteMonitoredProjectRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteMonitoredProject(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "MetricsScopes_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `MetricsScopesClient`.
  ///
  /// To mock `MetricsScopesClient` change your functions to receive
  /// `some MetricsScopesProtocol` or `any MetricsScopesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol MetricsScopesProtocol: Sendable {
    /// See `MetricsScopesClient.getMetricsScope`.
    func getMetricsScope(
      request: GetMetricsScopeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope

    /// See `MetricsScopesClient.listMetricsScopesByMonitoredProject`.
    func listMetricsScopesByMonitoredProject(
      request: ListMetricsScopesByMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse

    /// See `MetricsScopesClient.createMonitoredProject`.
    func createMonitoredProject(
      request: CreateMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MetricsScopesClient.createMonitoredProject`.
    func createMonitoredProjectPollingUntilDone(
      request: CreateMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<MonitoredProject>

    /// See `MetricsScopesClient.deleteMonitoredProject`.
    func deleteMonitoredProject(
      request: DeleteMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `MetricsScopesClient.deleteMonitoredProject`.
    func deleteMonitoredProjectPollingUntilDone(
      request: DeleteMonitoredProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>
  }
}

// Default implementations
extension Clients.MetricsScopesProtocol {
  public func getMetricsScope(request: GetMetricsScopeRequest) async throws
    -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope
  {
    try await self.getMetricsScope(request: request, options: .init())
  }

  public func getMetricsScope(
    request: GetMetricsScopeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getMetricsScope(
    name: Swift.String,
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.MetricsScope {
    let request = GetMetricsScopeRequest().with {
      $0.name = name
    }
    return try await self.getMetricsScope(request: request)
  }

  public func listMetricsScopesByMonitoredProject(
    request: ListMetricsScopesByMonitoredProjectRequest
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse
  {
    try await self.listMetricsScopesByMonitoredProject(request: request, options: .init())
  }

  public func listMetricsScopesByMonitoredProject(
    request: ListMetricsScopesByMonitoredProjectRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringMetricsScopeV1.ListMetricsScopesByMonitoredProjectResponse
  {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createMonitoredProject(request: CreateMonitoredProjectRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createMonitoredProject(request: request, options: .init())
  }

  public func createMonitoredProject(
    request: CreateMonitoredProjectRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createMonitoredProjectPollingUntilDone(request: CreateMonitoredProjectRequest)
    async throws -> any GoogleGax.PollableOperation<MonitoredProject>
  {
    try await self.createMonitoredProjectPollingUntilDone(request: request, options: .init())
  }

  public func createMonitoredProjectPollingUntilDone(
    request: CreateMonitoredProjectRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<MonitoredProject> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<MonitoredProject>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createMonitoredProjectPollingUntilDone(
    parent: Swift.String,
    monitoredProject: MonitoredProject?,
  ) async throws -> any GoogleGax.PollableOperation<MonitoredProject> {
    let request = CreateMonitoredProjectRequest().with {
      $0.parent = parent
      $0.monitoredProject = monitoredProject
    }
    return try await self.createMonitoredProjectPollingUntilDone(request: request)
  }

  public func deleteMonitoredProject(request: DeleteMonitoredProjectRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteMonitoredProject(request: request, options: .init())
  }

  public func deleteMonitoredProject(
    request: DeleteMonitoredProjectRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteMonitoredProjectPollingUntilDone(request: DeleteMonitoredProjectRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteMonitoredProjectPollingUntilDone(request: request, options: .init())
  }

  public func deleteMonitoredProjectPollingUntilDone(
    request: DeleteMonitoredProjectRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteMonitoredProjectPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteMonitoredProjectRequest().with {
      $0.name = name
    }
    return try await self.deleteMonitoredProjectPollingUntilDone(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
